### ISSUE TITLE
SCT Failure with BS.AllocatePool - Type is EfiMaxMemoryType 

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/bbr-acs#41]
In the SCT test, we get an error “BS.AllocatePool - Type is EfiMaxMemoryType – FAILURE 99F47EDE-57C9-4892-943E-F0F508B23B91”.  
We believe that the test should be compiled against a newer stable tag to pull https://github.com/tianocore/edk2/commit/502c01c5028038e4e6b4512e9c66be0ec4d11492.  

```
BS.AllocatePool - Type is EfiMaxMemoryType -- FAILURE
99F47EDE-57C9-4892-943E-F0F508B23B91
/home/marc/devel/ampere/arm-systemready/SR/scripts/edk2-test/uefi-sct/SctPkg/TestCase/UEFI/EFI/BootServices/MemoryAllocationServices/BlackBoxTest/MemoryAllocationServicesBBTestConformance.c:953:Status - Success

```

**Comment by edhay** [comment]
Hi Sunny, 
Thank you for reporting. We are looking at the issue and will provide updates soon.

**Comment by edhay** [comment]
The issue is due to mismatch of the value EfiMaxMemoryType, which is used as parameter to define a invalid case testing for SCT AllocatePool() test. 
UEFI-SCT, built as part of ACS used an older version of edk2 and hence reflected the older value of EfiMaxMemoryType.
Now version of edk2 has been upgraded to take the updated value.

The upgrade is done by the below commit:
https://github.com/ARM-software/arm-systemready/commit/cf3fa8b1921c41af10c14cc302dee67ba7eda3a4
